import { afterEach, expect, it } from "bun:test";
import { startTestServer, type TestServer } from "./harness.ts";
import { getUserByName } from "../users.ts";
import { mintAgentToken } from "../identity/tokens.ts";
import type { MembersChatMessage } from "../../shared/types.ts";
let server: TestServer | undefined;
afterEach(async () => { await server?.stop(); server = undefined; });

it("sets each member's reaction idempotently and emits updates without changing readers", async () => {
  const srv = server = await startTestServer();
  const owner = await srv.seedOwner("Nil");
  const member = await srv.seedMember("Pau");
  const nilId = getUserByName("Nil")!.id;
  const pauId = getUserByName("Pau")!.id;
  const request = (method: string, path: string, body: unknown, rawSessionId = owner.rawSessionId) =>
    srv.http(path, { method, rawSessionId, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const posted = await request("POST", "/api/members-chat", { text: "React here" });
  const message = await posted.json() as MembersChatMessage;
  await request("POST", "/api/members-chat/read", { lastReadId: message.id });
  const socket = await srv.connectWs(member.rawSessionId);
  await socket.waitFor("full_state");
  const path = `/api/members-chat/${message.id}/thumbs-up`;
  const set = await request("PUT", path, { active: true, userId: pauId, kind: "agent", userName: "Spoof" });
  expect(set.status).toBe(200);
  const reacted = await set.json() as MembersChatMessage;
  expect(reacted.thumbsUp).toEqual([{ kind: "user", userId: nilId, userName: "Nil" }]);
  expect(await socket.waitFor("members_chat_message")).toMatchObject({ updateOnly: true, message: reacted });
  expect((await (await request("PUT", path, { active: true })).json()).thumbsUp).toEqual(reacted.thumbsUp);
  const second = await (await request("PUT", path, { active: true }, member.rawSessionId)).json();
  expect(second.thumbsUp.map((r: { userId: string }) => r.userId)).toEqual([nilId, pauId]);
  const unset = await (await request("PUT", path, { active: false })).json();
  expect(unset.thumbsUp).toEqual([{ kind: "user", userId: pauId, userName: "Pau" }]);
  expect((await (await srv.http("/api/members-chat", { rawSessionId: owner.rawSessionId })).json()).unread).toBe(0);
  expect((await (await srv.http("/api/members-chat", { rawSessionId: member.rawSessionId })).json()).unread).toBe(1);
  expect((await request("PUT", path, { active: "true" })).status).toBe(400);
  await request("DELETE", `/api/members-chat/${message.id}`, {});
  expect((await request("PUT", path, { active: true })).status).toBe(404);
  expect((await request("PUT", "/api/members-chat/202609-00000000/thumbs-up", { active: true })).status).toBe(404);
  socket.close();
  const editSocket = await srv.connectWs(member.rawSessionId);
  await editSocket.waitFor("full_state");
  const another = await (await request("POST", "/api/members-chat", { text: "Edit me" })).json();
  await editSocket.waitFor("members_chat_message");
  editSocket.messages.length = 0;
  await request("PATCH", `/api/members-chat/${another.id}`, { text: "Edited" });
  expect(await editSocket.waitFor("members_chat_message")).toMatchObject({ updateOnly: true, message: { content: "Edited" } });
  editSocket.close();
});

it("uses the existing guard and preserves privileged-agent and API reactor attribution", async () => {
  const srv = server = await startTestServer();
  const owner = await srv.seedOwner("Nil");
  const userId = getUserByName("Nil")!.id;
  const post = await srv.http("/api/members-chat", { method: "POST", rawSessionId: owner.rawSessionId, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: "Attribution" }) });
  const message = await post.json() as MembersChatMessage;
  const roomId = srv.agentManager.getRooms()[0].id;
  const bot = await srv.agentManager.spawn("Helper", srv.stateRoot, "default", undefined, undefined, roomId, undefined, undefined, undefined, undefined, "codex");
  expect(!!bot).toBe(true);
  const path = `/api/members-chat/${message.id}/thumbs-up`;
  const react = (bearer: string, active = true) => srv.http(path, { method: "PUT", headers: { Authorization: `Bearer ${bearer}`, "Content-Type": "application/json" }, body: JSON.stringify({ active, userName: "Spoof", kind: "user" }) });
  expect((await react(mintAgentToken(bot!.id, userId, false))).status).toBe(403);
  const privileged = mintAgentToken(bot!.id, userId, true);
  const response = await react(privileged);
  expect(response.status).toBe(200);
  expect((await response.json()).thumbsUp).toEqual([{ kind: "agent", userId, userName: "Helper" }]);
  await react(privileged, false);
  const minted = await srv.http("/api/me/api-tokens", { method: "POST", rawSessionId: owner.rawSessionId, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Phone", expiresInDays: 30 }) });
  const { token } = await minted.json();
  const api = await react(token);
  expect(api.status).toBe(200);
  expect((await api.json()).thumbsUp).toEqual([{ kind: "api", userId, userName: "Nil", device: "Phone" }]);
});
